development:
  adapter: postgresql
  encoding: unicode
  database: dpthomas_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: dpthomas_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: dpthomas_production
  pool: 5

cucumber:
  <<: *test
