development:
  adapter: postgresql
  encoding: unicode
  database: dpt_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: dpt_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: dpt_production
  pool: 5

cucumber:
  <<: *test
